### ISSUE TITLE
Start Docker-compose with Boot

### ISSUE THREAD

**Issue by ghost** [jrcichra/lancache-rpi#11]
Is there a way to make the container start automatically when the raspberry pi starts up?

**Comment by jrcichra** [comment]
Sure, you can add `restart: always` to each container in the yaml. That will start it across boots. We should make this the default. I'll keep this issue open and include that as a fix.

**Comment by ghost** [comment]
is this correct?

version: '3'
services:
  dns:
    image: jrcichra/lancachenet-lancache-dns:latest  ## Pulling DNS server for arm
    env_file: .env
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      restart: always
  sniproxy:
    image: jrcichra/lancachenet-sniproxy:latest  ## Pulling Sniproxy for arm
    env_file: .env
    ports:
      - 443:443/tcp
      restart: always
  monolithic:
    image: jrcichra/lancachenet-monolithic:latest ## Pulling monolithic for arm
    env_file: .env
    ports:
      - 80:80/tcp
      restart: always
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs

**Comment by jrcichra** [comment]
That should work. I just committed this fix: https://github.com/jrcichra/lancache-rpi/commit/9c6623578ec7454cffe3cecbf752f5a6516340ed

**Comment by ghost** [comment]
Maybe I did it wrong but when I added those lines to each section it didn't start automatically and then when I went to manually start it I got this error:
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yml", line 8, column 1

**Comment by ghost** [comment]
How do I update my repository? do I just pull from this line of code sudo git clone https://github.com/jrcichra/lancache-rpi.git?

**Comment by jrcichra** [comment]
Yes, if you already did a `git clone` before to create it, you should be able to do `git pull` from within the directory. Downloading another copy of the zip file works too.
