### ISSUE TITLE
cannt pull immage anymore 

### ISSUE THREAD

**Issue by mari0theminer** [jrcichra/lancache-rpi#12]
hey since the last patch i am unable to pull the image 

Pulling dns (jrcichra/lancachenet-lancache-dns:latest)...
latest: Pulling from jrcichra/lancachenet-lancache-dns
854ab59e811f: Pulling fs layer
996b7ca18b13: Pulling fs layer
50a08dcf8afc: Pulling fs layer
d34a2e7cb38e: Waiting
528f94627a01: Waiting
06585a47ffcf: Waiting
2d03e2bb05e6: Waiting
0f6baf0dcc90: Waiting
41018873be17: Waiting
789de1badef5: Waiting
0583026cfae6: Waiting
21ad4febaaf8: Waiting
032e46f00b13: Waiting
e58c91cd1ef2: Waiting
ERROR: error pulling image configuration: unknown blob

**Comment by jrcichra** [comment]
I can recreate it. Investigating...

**Comment by jrcichra** [comment]
Try now, I re-ran the last CI run and it fully passed. I'm wondering if Docker Hub was having issues, I'm seeing 400 Bad Requests in my logs.

I'll keep this open while I think of a better method of keeping the containers up to date without breaking production...even if I punt the pushes all to the end, I could still get a 400 Bad Request from Docker Hub...

Given their new pull policy, retention policy, and the potential popularity of this repo, I may just switch to the new Github Container Registry

**Comment by jrcichra** [comment]
I tried doing a shift but quickly pulled it back after getting an exec format error. I'm not sure if the Github Registry supports non-x86 architectures. I did try pulling from an arm64 Pi...

**Comment by jrcichra** [comment]
Looks like this is a bigger issue than just my CI. If it happens more frequently, I'll look into triggering delayed CI actions on failures to minimize image downtime.
