### ISSUE TITLE
9/30/20 monolithic image in a restart loop. "proxy_max_temp_file_size" directive invalid value

### ISSUE THREAD

**Issue by Avi0n** [jrcichra/lancache-rpi#14]
The latest monolithic build (9/30/20) included a change to increase `proxy_max_temp_file_size` from 1024m to 8192m. I am now getting the following error when trying to start the monolithic image:
```
Checking nginx config
nginx: [emerg] "proxy_max_temp_file_size" directive invalid value in /etc/nginx/sites-available/generic.conf.d/root/20_cache.conf:29
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'
```

I am running on a Raspberry Pi 4 with DietPi 64bit.

**Comment by jrcichra** [comment]
Sorry about that. I just switched it back. The CI should be building it now. I was diagnosing a different issue and broke the build. Since this repo is getting popular, I'll be working on tagged builds with a rolling :latest stable so this doesn't happen again.
