### ISSUE TITLE
Restarting

### ISSUE THREAD

**Issue by yob46** [jrcichra/lancache-rpi#19]
Lancache monolithic keeps on restarting and not caching anything

**Comment by the-maty** [comment]
I have the same problem. Both containers are restarting and nothing is caching

**Comment by jrcichra** [comment]
Ok. A regression must have come in from the automated builds. I'll take a look this evening and revisit my build strategy. Right now it always overwrites latest, and we can't easily jump back to old builds.

As a workaround, I've been running a good copy of the arm64 variant. I've tagged and pushed the containers with `:good`. This probably won't work with a 32 bit kernel Pi.

**Comment by jrcichra** [comment]
I was unable to recreate this on a Pi4 32bit. They've been up for a half hour:

```
pi@justinpi:~/git/lancache-rpi $ docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                      PORTS                           NAMES
84958c9b678f   jrcichra/lancachenet-monolithic:latest     "/bin/bash -e /init/…"   34 minutes ago   Up 33 minutes               0.0.0.0:80->80/tcp, 443/tcp     lancache-rpi_monolithic_1
da49fa7ee290   jrcichra/lancachenet-lancache-dns:latest   "/bin/bash -e /init/…"   34 minutes ago   Up 33 minutes               53/tcp, 10.0.0.149:53->53/udp   lancache-rpi_dns_1
029ec6f57c88   jrcichra/lancachenet-sniproxy:latest       "/scripts/bootstrap.…"   34 minutes ago   Up 33 minutes               0.0.0.0:443->443/tcp            lancache-rpi_sniproxy_1
a596f85f02f7   jrcichra/https-portal                      "/init"                  4 weeks ago      Exited (0) 51 minutes ago                                   proxy_https-portal_1
pi@justinpi:~/git/lancache-rpi $ doc^Cok
pi@justinpi:~/git/lancache-rpi $ docker images
REPOSITORY                          TAG       IMAGE ID       CREATED        SIZE
jrcichra/lancachenet-lancache-dns   latest    7237adda8518   4 hours ago    462MB
jrcichra/lancachenet-sniproxy       latest    42aca66588d8   4 hours ago    6.22MB
jrcichra/lancachenet-monolithic     latest    6b4559cbe0ee   4 hours ago    465MB
aptman/qus                          latest    884e4a3f23ec   13 days ago    250MB
jrcichra/https-portal               latest    07e240cdbe18   3 months ago   233MB
pi@justinpi:~/git/lancache-rpi $ 
```

What container version are you using / what's the output in `docker-compose logs -f`?

**Comment by the-maty** [comment]
I fully reinstalled my Pi and its working without any issue. I just have one question. What is potential max speed of downloading games from lancache?

**Comment by jrcichra** [comment]
According to this issue: https://github.com/jrcichra/lancache-rpi/issues/7, the Pi seems to cap out at ~50MB/s.

**Comment by the-maty** [comment]
Should I try to set it up on 64bit os? What OS should I use with my raspberry pi 4 with 4gb ram?

**Comment by jrcichra** [comment]
64 bit would be preferred. The ubuntu image makes it easy to grab a 64 bit os: https://ubuntu.com/download/raspberry-pi

**Comment by the-maty** [comment]
> 64 bit would be preferred. The ubuntu image makes it easy to grab a 64 bit os: https://ubuntu.com/download/raspberry-pi

Which version should I choose?

**Comment by jrcichra** [comment]
I would go with `Ubuntu Server 20.04.1 LTS` unless you want a GUI.
