### ISSUE TITLE
not caching

### ISSUE THREAD

**Issue by CyberoniOntoni** [jrcichra/lancache-rpi#2]
the instance runs perfectly:

> C:\Users\Admin>nslookup lancache.steamcontent.com
> Server:  UnKnown
> Address:  192.168.31.220
> 
> Non-authoritative answer:
> Name:    steam.cache.lancache.net
> Address:  192.168.31.220
> Aliases:  lancache.steamcontent.com

for some reason not caching any chunks from any service (ipv6 off). 
all tests from http://diagnostics.lancache.net/ come negative.

**Comment by jrcichra** [comment]
I'll take a look at it this weekend. It's possible my daily cron that checks for updates could have some bug in it. We can look at ways for the CI to `assert` an nslookup before it pushes the latest tag.

**Comment by jrcichra** [comment]
Bugs as in it takes master of all the git repos at who knows what stability. I haven't pulled latest in awhile.

**Comment by jrcichra** [comment]
The 64 bit version might be bugged - I tried 32 bit:
```
root@f559b04882cb:/# nslookup lancache.steamcontent.com
Server:		10.0.0.218
Address:	10.0.0.218#53

Non-authoritative answer:
lancache.steamcontent.com	canonical name = steam.cache.lancache.net.
Name:	steam.cache.lancache.net
Address: 10.0.0.218

root@f559b04882cb:/# ```

**Comment by jrcichra** [comment]
Tried in a windows vm with the 32 bit version on a pi - maybe you can try that?
![image](https://user-images.githubusercontent.com/1342149/77219744-d70eb180-6b0e-11ea-9edb-7a3ff637f65f.png)

**Comment by jrcichra** [comment]
If you pull latest after this run finishes it should work for you: https://github.com/jrcichra/lancache-rpi/runs/523586864?check_suite_focus=true

**Comment by jrcichra** [comment]
Also do a git pull, I updated one of the tags

**Comment by CyberoniOntoni** [comment]
![image](https://user-images.githubusercontent.com/58321719/77225832-3c10e880-6b9d-11ea-8466-57a134711490.png)
fixed, Thanks!
