### ISSUE TITLE
Monolithic Container is Stuck in a Endless Loop of High CPU Usage and Restarting

### ISSUE THREAD

**Issue by muckyfeet** [jrcichra/lancache-rpi#24]
Since I pulled the latest images yesterday, One of the containers ([jrcichra/lancachenet-monolithic:latest](https://hub.docker.com/layers/jrcichra/lancachenet-monolithic/latest/images/sha256-86f7f9193faa10ca668035fc307127a464e55a6ad3baed415711fcc4ba9c413b?context=explore)) has been stuck in a loop of using around one hundred and thirty percent of the CPU and restarting.

I tried pulling the latest image that was pushed around eight hours ago again this morning with the same symptoms.

<img width="1526" alt="Screen Shot 2021-10-29 at 09 14 09" src="https://user-images.githubusercontent.com/1675319/139400424-d8405e7e-910e-4eea-ae4a-066781177eb1.png">

https://user-images.githubusercontent.com/1675319/139400524-be92a022-34a9-4e29-93c7-5693965f0455.mov

**Comment by jrcichra** [comment]
I got the same issue on my raspberry pi. Here's what I'm seeing in the logs:
```
nginx: [emerg] "proxy_max_temp_file_size" directive invalid value in /etc/nginx/sites-available/cache.conf.d/root/20_cache.conf:33
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'
```

It's unhappy with the temp file size value I have. I'll investigate.

**Comment by jrcichra** [comment]
Ok - I needed to update this file with the right `proxy_max_temp_file_size`: https://github.com/lancachenet/monolithic/blob/master/overlay/etc/nginx/sites-available/cache.conf.d/root/20_cache.conf.

Now when I pull the latest `monolithic` it stays up and there's no error.

**Comment by billiamg** [comment]
Hi - I pulled the latest update last night (I accidently nuked my pi a few days back). I'm getting the following error (which I believe is the same as you quoted above) when attempting to deply.

`monolithic_1  | # Finished including /etc/nginx/nginx.conf
monolithic_1  | Checking nginx config
monolithic_1  | nginx: [emerg] "proxy_max_temp_file_size" directive invalid value in /etc/nginx/sites-available/cache.conf.d/root/20_cache.conf:33
monolithic_1  | nginx: configuration file /etc/nginx/nginx.conf test failed
monolithic_1  | ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'
`

**Comment by jrcichra** [comment]
Interesting. It could be the automated nightly builds are causing more trouble than they're worth. I'll debug and moving forward will stick to manually tested builds.

**Comment by billiamg** [comment]
No worries, my deployment isn't super important but with the coming release of Battlefield, I think caching that will be helpful.

I don't think it's related, but my previous deployment was in tandem with a PiHole container. I think I tested without the PiHole container deployed and had the same experience (albeit prior to this most recent change). 

Appreciate the work you've done on this, it was pretty flawless before I did an rm * on my pi.

**Comment by jrcichra** [comment]
@billiamg here are the images that are stable for me. Are you on these shas?
```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
jrcichra/lancachenet-lancache-dns   latest              9b0abd89979c        21 hours ago        463MB
jrcichra/lancachenet-monolithic     latest              1e47d393a1b7        21 hours ago        467MB
```

I'm testing this on Raspberry Pi OS (32 bit)

**Comment by billiamg** [comment]
@jrcichra just checked - I think they're old. Deleted and redeploying now. Wil update comment with results. Hopefully if that's the issue it didn't waste too much of your time.

Edit: Welp, that was it. Now it's just time to piece back together how I had routed PiHole -> Lancache -> internet :D

**Comment by jrcichra** [comment]
Great! Glad I could help. Leaving this open. @Muckyfeet any success on the latest pull?

**Comment by muckyfeet** [comment]
The image I pulled last Wednesday seems to be working great.

```
REPOSITORY                          TAG       IMAGE ID       CREATED      SIZE
jrcichra/lancachenet-lancache-dns   latest    a5565ff5dcb3   3 days ago   463MB
jrcichra/lancachenet-monolithic     latest    1c65e6ec6b27   3 days ago   467MB
```
I havant pulled anything newer. Do you want me to try again now?

**Comment by jrcichra** [comment]
If it's working great on that SHA that's good :). There were a couple nightly builds between when I fixed it and now. I've disabled the nightly builds for now, and will qualify updates every so often.
