### ISSUE TITLE
Slower than expected cache speeds?

### ISSUE THREAD

**Issue by Swindyyy** [jrcichra/lancache-rpi#7]
Hi, this isn't so much a major bug but more so a question of the speeds I'm supposed to get while using this with a RPi 4B+.

I've set up everything according to the instructions, its clearly working as I jump from ~20MB/s to ~50MB/s. I was just wondering if you've been able to get nearer the 100MB/s mark.

The drive I'm using is an SSD connected via a Quad Sata HAT and running a benchmark of the drive, I should be able to hit 100MB/s sequential reads.

**Comment by jrcichra** [comment]
What service are you caching, or is it just across the board? I'll give it a try on my Pi4 - we can look at htop usage.

**Comment by Swindyyy** [comment]
I was using Steam, and using XCOM Chimera Squad as the baseline.

I ran the test multiple times and it kept capping at around the 50 mark.
Shouldn't be a bottle neck on the drive I'm installing to as that's an NVMe
drive.

**Comment by jrcichra** [comment]
Yeah I had a friend confirm and we are seeing lower than expected speeds, even with the cache sitting in a ramdisk. I'm digging in some more, maybe changing CACHE_SLICE_SIZE would help?

The pi/software might not be tuned for this workload (will have to check my compilation).

**Comment by CyberoniOntoni** [comment]
You need to fine tune your chunk size. 
[Source](http://lancache.net/docs/advanced/tuning-cache/#b---tweaking-slice-size)
"The default of 1MB is considered the safest, but increasing to 2, 4 or even 8 might give performance improvements for single-user download scenarios without too many adverse effects."

**Comment by jrcichra** [comment]
Closing and recommending you increase the chunk size. Please reopen if this doesn't solve the issue.

**Comment by Swindyyy** [comment]
Sorry about the delayed.  I had to redo the entire NAS set up as one of my drives died. I'm trying to change the CACHE_SLICE_SIZE but every time I add it into the .env file, the monolithic container wont start up

Edit: Just reading through the other threads about monolithic failing and I'm not doing anything with FAT, my drive is formatted EXT4 and only fails when I add in this cache_slice variable

**Comment by jrcichra** [comment]
@Swindyyy Adding this as the last line in the .env file for me didn't crash the container:

`CACHE_SLICE_SIZE=4m`

**Comment by Swindyyy** [comment]
Just to confirm your steps

`sudo nano .env` 
Add `CACHE_SLICE_SIZE=4m`
Save .env
`docker-compose up -d`

Are these correct?

**Comment by jrcichra** [comment]
That's correct. What is the output from `docker logs lancache-rpi_monolithic_1` if that still fails?

**Comment by Swindyyy** [comment]
Ah the log is pointing the issue. It's failing to not invalidate the cache. I'll delete the cache and report back

**Comment by Swindyyy** [comment]
Just going to link this as it was relevant to my problem: http://lancache.net/docs/advanced/config-hash/

As for my speeds, increasing to `CACHE_SLICE_SIZE=4m` and `CACHE_SLICE_SIZE=8m` haven't yielded improvements. I still cap out at 50MB/s. I'm tryna an alternate launcher but I now seem to be having issues with Battle.net being horrendously slow at even just doing the initial starting downloading (Fetching encoding table/fetching index/fetching indices etc)

**Comment by Swindyyy** [comment]
So I'm just providing an update here because I've finally been able to get back around to closing this off, changing my cache slize size to 8M isn't a fix so I can only assume that the Pi isn't up to handling this workload. Not sure if you want to close the issue after this but I'm ok with it being closed. Upping my slice size did help with my Battle.net speeds though (a little bit!)

**Comment by jrcichra** [comment]
Sure, I'll close out this issue. I've made a note on the homepage addressing it: https://github.com/jrcichra/lancache-rpi/commit/18949361961116754ac147eccfc5ccce64d67ef8

There's definitely some abstract bottleneck on the Pi. Maybe running a arm64 OS, like Ubuntu, would yield better results.
