### ISSUE TITLE
lancache-rpi_monolithic_1 keeps failing

### ISSUE THREAD

**Issue by NeonDerg** [jrcichra/lancache-rpi#8]
As the title says the lancache-rpi_monolithic_1 keeps failing. When checking the logs I get

nginx: [emerg] chown("/data/cache/cache", 33) failed (1: operation not permitted)
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'

I'm a noob at anything linux related so help would very much be appreaciated.

**Comment by jrcichra** [comment]
Sure, can you paste the output of `docker images`? I want to see what SHA-256 layers your `docker pull` happened to get and see if I can recreate the issue.

Did you change anything in the .env file? Make sure wherever the lancache directory is in that env that you have permissions to write there. Maybe precreate the directory with `sudo mkdir <dirname>` and `chmod 666 <dirname>`

**Comment by NeonDerg** [comment]
I'll post it tomorrow. Just went home for the day and this is something I'm fiddling around with at school.

**Comment by NeonDerg** [comment]
Output of docker images.

REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
jrcichra/lancachenet-lancache-dns   latest              5cb6b33ea9cd        31 hours ago        456MB
jrcichra/lancachenet-sniproxy       latest              43ac8ca8eb7f        31 hours ago        5.81MB
jrcichra/lancachenet-monolithic     latest              6b8cb4410e0a        31 hours ago        460MB
lancachenet/monolithic              latest              cee83d5f2e74        12 days ago         592MB
lancachenet/lancache-dns            latest              e3993ccf9cb8        12 days ago         589MB
lancachenet/sniproxy                latest              f4c2e1bd9718        8 weeks ago         7.86MB

Thanks in advance!

**Comment by NeonDerg** [comment]
after trying both chmod 777 and 666 on both /media/ubuntu/CACHE and CACHE/lancache I now get this again.

Checking nginx config
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] chown("/data/cache/cache", 33) failed (1: Operation not permitted)
nginx: configuration file /etc/nginx/nginx.conf test failed
ERROR: hook /hooks/supervisord-pre.d/99_config_check.sh} returned a non-zero exit status '0'

Not sure if me trying to put the cache on my external drive has anything to do with it.

**Comment by NeonDerg** [comment]
Got it to work by enabling mount at startup on my disk. I don't think it's caching anything though?

**Comment by jrcichra** [comment]
You can check the access logs with `sudo docker exec -it <monolithic_container_name> tail -f /data/logs/access.log | ccze -A`. You have to set your computer's DNS to use the lancache, it won't work magically without DNS at some level.

**Comment by NeonDerg** [comment]
I've set up the computers DNS. the problem was it wasn't actually caching to the location I thought it was. After enabling mount at startup the address to my drive changed and after changing it in .env I'm now back with the same error

**Comment by jrcichra** [comment]
It's definitely some permissions mismatch: `nginx: [emerg] chown("/data/cache/cache", 33) failed (1: Operation not permitted)`

Does it start up properly if you put it on the local SD card?

**Comment by NeonDerg** [comment]
It did that's when I sent that I got it to work. But I've now managed to fuck up my entire file system. (Don't ask I had a retarded moment) I'm starting over and trying out raspbian since ubuntu had a ton of problems on the RPI4.

**Comment by jrcichra** [comment]
I've only tested this on raspbian buster, I can't speak for support of Ubuntu. Ubuntu might have stricter usb udev permissions. I think raspbian is more relaxed.

**Comment by NeonDerg** [comment]
Getting same issue on raspbian. Does me running FAT32 on the disk have anything to do with it?

**Comment by NeonDerg** [comment]
Changed to Raspbian Buster and an NTFS filesystem on the cache drive. Monolithic now works but instead getting 
ERROR: for lancache-rpi_dns_1 Cannot start service dns: driver failed programming external connectivity on endpoint lancache-rpi_dns_1 (72975bd8466539a7fd40c60eb3987bf4fea4973ba2abdb5f787fa1f34a2aaa7): Error starting userland: proxy listen udp 192.168.123.1:53: bind cannot assign requested address

ERROR: for dns  Cannot start service dns: driver failed programming external connectivity on endpoint lancache-rpi_dns_1 (72975bd8466539a7fd40c60eb3987bf4fea4973ba2abdb5f787fa1f34a2aaa7): Error starting userland: proxy listen udp 192.168.123.1:53: bind cannot assign requested address

**Comment by jrcichra** [comment]
Could be something else is on port 53 (dnsmasq)? what does `lsof -i :53` say?

**Comment by NeonDerg** [comment]
lsof -i :53 does not give me a reply

**Comment by NeonDerg** [comment]
![IMG_20200515_091020](https://user-images.githubusercontent.com/65223192/82021863-ef70f780-968b-11ea-8fdf-644b03c2f666.jpg)
Could this have anything to do with it?

**Comment by NeonDerg** [comment]
I give up

**Comment by jrcichra** [comment]
@NeonDerg https://github.com/jrcichra/lancache-rpi/issues/10#issuecomment-650591835

Someone else had a similar issue with a FAT32 external drive. I don't believe lancache itself, or `nginx`, the caching engine, supports Microsoft formatted filesystems to house the cache.

**Comment by jrcichra** [comment]
So if you can format the drive to `ext4`, that works for me. Keep in mind formatting the drive means you'll lose all the data on it and if `ext4` it will only be recognizable to linux systems.
